version: '3.9'

services:
  be-short:
    container_name: be-short
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=docker
      - PORT=8080
      - LOG_LEVEL=debug
    ports:
      - "8080:8080"
    networks:
      - be-short-network
  be-short-db:
    container_name: be-short-db
    image: mongo:latest
    networks:
      - be-short-network
    ports:
      - "27017:27017"
networks:
  be-short-network:
    driver: bridge