version: '3.9'

services:
  be-short:
    container_name: be-short
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=docker
      - PORT=1323
      - LOG_LEVEL=debug
    ports:
      - "1323:1323"
    networks:
      - be-short-network
networks:
  be-short-network:
    driver: bridge