name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Unit_Tests:
    name: Unit Tests
    strategy:
      matrix:
        go-version: [ 1.21.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run Test
        run: |
          go test -v -covermode=count -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out -o=coverage.out